-- =============================================
-- AI PENDING NOTES TABLE
-- Stores @update notes generated by AI for lead source sync
-- Run this in Supabase SQL Editor
-- =============================================

-- Create the ai_pending_notes table
CREATE TABLE IF NOT EXISTS ai_pending_notes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    person_id INTEGER NOT NULL,
    note_type TEXT NOT NULL,  -- 'timeline', 'budget', 'pre_approval', 'areas', 'motivation', 'property_type', 'current_situation'
    note_content TEXT NOT NULL,  -- The formatted @update note content
    raw_value TEXT,  -- The raw extracted value (e.g., "0-3 months", "$525000")
    confidence FLOAT DEFAULT 0.0,  -- Confidence score from AI extraction (0.0-1.0)
    status TEXT DEFAULT 'pending',  -- 'pending', 'approved', 'dismissed', 'sent'
    extracted_from_message_id UUID,  -- References ai_message_log(id) if available
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by TEXT,  -- Email of user who reviewed
    fub_note_id INTEGER,  -- FUB note ID after creation
    error_message TEXT  -- Error if note creation failed
);

-- Create indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_ai_pending_notes_person ON ai_pending_notes(person_id);
CREATE INDEX IF NOT EXISTS idx_ai_pending_notes_status ON ai_pending_notes(status);
CREATE INDEX IF NOT EXISTS idx_ai_pending_notes_created ON ai_pending_notes(created_at DESC);

-- Add comments
COMMENT ON TABLE ai_pending_notes IS 'Stores @update notes generated by AI from extracted lead data. Notes are queued for review before syncing to lead sources.';
COMMENT ON COLUMN ai_pending_notes.note_type IS 'Type of data extracted: timeline, budget, pre_approval, areas, motivation, property_type, current_situation';
COMMENT ON COLUMN ai_pending_notes.note_content IS 'The formatted note content with @update prefix';
COMMENT ON COLUMN ai_pending_notes.confidence IS 'AI confidence score for the extraction (0.0-1.0)';
COMMENT ON COLUMN ai_pending_notes.status IS 'Workflow status: pending, approved, dismissed, sent';

-- Disable RLS for service role access (same pattern as other AI tables)
ALTER TABLE ai_pending_notes DISABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON ai_pending_notes TO service_role;
GRANT ALL ON ai_pending_notes TO authenticated;


-- =============================================
-- AI ACTIVITY LOG TABLE (for activity feed)
-- =============================================

CREATE TABLE IF NOT EXISTS ai_activity_log (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    person_id INTEGER NOT NULL,
    activity_type TEXT NOT NULL,  -- 'message_sent', 'message_received', 'state_changed', 'escalated', 'paused', 'resumed', 'note_created'
    activity_data JSONB,  -- Additional data specific to activity type
    description TEXT NOT NULL,  -- Human-readable description
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_ai_activity_log_person ON ai_activity_log(person_id);
CREATE INDEX IF NOT EXISTS idx_ai_activity_log_created ON ai_activity_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_activity_log_type ON ai_activity_log(activity_type);

-- Add comment
COMMENT ON TABLE ai_activity_log IS 'Logs AI activity events for the monitoring dashboard activity feed';

-- Disable RLS
ALTER TABLE ai_activity_log DISABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON ai_activity_log TO service_role;
GRANT ALL ON ai_activity_log TO authenticated;


-- =============================================
-- VERIFICATION
-- =============================================

-- Check ai_pending_notes structure
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'ai_pending_notes'
ORDER BY ordinal_position;

-- Check ai_activity_log structure
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'ai_activity_log'
ORDER BY ordinal_position;
